### ISSUE TITLE
Deploy directories

### ISSUE THREAD

**Issue by hmaurer** [GoBoundless/spar#11]
Hello there,

I noticed that when deploying, all the files are outputted in the same directory. Is there a way to force the images to go into compiled/production/images, and so on ?

Also, is there a way to disable the md5-hash automatically added to the deployed filed names ?

Thanks and great job on spar!

**Comment by mhodgson** [comment]
Hi there, 

Right now Spar views all assets as the same type and therefor just dumps them all in the same directory. This is consistent with how the rails asset pipeline works, and how sprockets is built. 

You should be able to turn off the asset digests by setting the digest config variable to false. 

Hope this helps!
