### ISSUE TITLE
sass image_url, etc not working

### ISSUE THREAD

**Issue by botandrose** [GoBoundless/spar#13]
Howdy! The compass and sprockets-sass `image_url` etc helpers have a different arity than the helpers defined in `Sprockets::Context`, and thus, fail. A partial workaround is to include the `sprockets-helpers` gem, but then this doesn't take into account the digest, and then it expects the compiled asset to be living in /assets instead of /.

I'm not quite sure the best way to solve this... perhaps define some Spar-specific `image_url` etc helpers? What do you think?

**Comment by mhodgson** [comment]
Hi there, Check out version 1.0.8. I added some spar specific helpers and made sure they override the ones included in the default sprockets context. Let me know how it works!

-Matt

**Comment by botandrose** [comment]
Wow, quick turnaround! I can confirm that it fixes image_url, and that the digests now work as expected in different environments. Compass sprites are still missing their digests in production, but I'll open a separate issue for that.
