### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by botandrose** [GoBoundless/spar#15]
Makes me nervous, contributing to a project without tests! I don't know if my pull requests will break things...

**Comment by mhodgson** [comment]
I hear you. Tests definitely need to be written. If you want to contribute some I'd love it ;-) 

Otherwise we'll probably get to it soon.

-Matt

**Comment by botandrose** [comment]
I'll see what I can do. :) I'd at least like to submit some tests for the compass-related stuff. I guess first things first, we should make some broad strokes to lay down the foundation for more, later.

I'm thinking black box acceptance tests for `spar server` and `spar deploy` would be the first step, just to get a handle on overall correctness. My first inclination is to use Cucumber + Capybara for the former, and Cucumber + Aruba for the latter, but not everyone loves the Cukes. What do you think?

**Comment by mhodgson** [comment]
That sounds perfect. I've used Cuke, Capy, and Aruba before. Thanks!

**Comment by botandrose** [comment]
Derp. Just noticed that you already have a Cucumber and Aruba scenario.
