### ISSUE TITLE
spar always executes new command

### ISSUE THREAD

**Issue by ChrisRicca** [GoBoundless/spar#4]
I just executed `spar server` inside a spar app and got the following output:

`spar server`
      create  server
      create  server/Gemfile
      create  server/README
      create  server/Rakefile
      create  server/app/assets/javascripts/javascript.js.coffee
      create  server/app/assets/stylesheets/application.css.sass
      create  server/app/views/index.haml
      create  server/config.ru
      create  server/config/application.rb
      create  server/script/server
         run  chmod +x script/\* from "./server"
      create  server/public
      create  server/public/.gitkeep
      create  server/lib
      create  server/lib/tasks
      create  server/lib/tasks/.gitkeep
      create  server/lib/assets
      create  server/lib/assets/.gitkeep
      create  server/app/assets/images
      create  server/app/assets/images/.gitkeep
      create  server/vendor/assets/javascripts
      create  server/vendor/assets/javascripts/.gitkeep
      create  server/vendor/assets/stylesheets
      create  server/vendor/assets/stylesheets/.gitkeep
A new Spar app has been created in server - Have Fun!

**Comment by ChrisRicca** [comment]
I should mention I am running the spar gem available when using `gem install spar`, my version is spar (0.2.7)

**Comment by mhodgson** [comment]
Hi Chris, I just pushed version 1.0.0 to rubygems.org. Update your gem and try again. We basically rewrote the whole thing and its totally different from 0.2.7.
