### ISSUE TITLE
Sprockets inclusion doesn't respect order

### ISSUE THREAD

**Issue by briannelson** [GoBoundless/spar#9]
In my application.css.sass file, I have: 

```
 //= require bootstrap/docs/assets/css/bootstrap
 //= require_self
 //= require_tree .
```

but when I am running my server locally, it adds to the page as:

```
<link href="/application.css?body=1" rel="stylesheet">
<link href="/bootstrap/docs/assets/css/bootstrap.css?body=1" rel="stylesheet">
```

Am I doing something wrong? Is there a way to get my styles to appear _after_ the bootstrap stuff?

**Comment by mhodgson** [comment]
Hi Brian, I'm seeing the same thing. Working on a fix now.

**Comment by briannelson** [comment]
Great! Thanks for the speedy reply. So far, I'm loving Spar. Any plans to include SCSS as well? (pretty please?)

**Comment by mhodgson** [comment]
Give it a shot. It should work out of the box if you have a .scss filename.

**Comment by mhodgson** [comment]
Brian, do mind creating a public repo I can check out that reproduces your problem? I'm unable to reproduce what you're seeing. Thanks!

**Comment by briannelson** [comment]
Here you go: https://github.com/digitalworkbox/digitalworkbox-site

**Comment by mhodgson** [comment]
Brian, I'm still not able to reproduce. Are you running spar 1.0.5?

**Comment by briannelson** [comment]
I just installed it today. Maybe there's something funky going on on my end. Thanks for taking a look!

**Comment by briannelson** [comment]
So, I went back to it and things seem to be working fine now? It must have been some weird caching thing, though I have my caching turned off in Safari.

Sorry to have you spend some time on this. Consider it closed.
